
project_id = "csixccpoxpnwowbgkoyw"

[functions]
[functions.make-outbound-call]
verify_jwt = true

[functions.call-webhook]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[functions.process-openai]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.voice-websocket]
verify_jwt = false

[functions.assistants]
verify_jwt = true

[functions.squads]
verify_jwt = true

[functions.analytics]
verify_jwt = true

[functions.provider-keys]
verify_jwt = true

[functions.support-ticket]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.end-call]
verify_jwt = true
