project_id = "csixccpoxpnwowbgkoyw"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.deepgram-voice-agent]
verify_jwt = false

[edge_runtime]
policy = "per_worker"
